name: Pipeline

run-name: ${{ github.actor }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci # --no-audit --no-fund --omit=optional
    - run: npx lint-staged
    - run: npm run build --if-present
    - run: npm test
    - run: npm run cy-run
    # - name: Cypress run
    #   uses: cypress-io/github-action@v4
    #   with:
    #       browser: chrome
    - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.